name: Test SSH Staging

on:
  push:
    branches:
      - feature-deployment
  workflow_dispatch:

jobs:
  ssh-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Test SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOSTINGER_STAGING_HOST }}
          username: ${{ secrets.HOSTINGER_STAGING_USER }}
          port: 65002
          key: ${{ secrets.HOSTINGER_SSH_KEY }}
          script: |
            echo "Connexion SSH réussie sur staging"
